### ISSUE TITLE
Blank lines don't survive copy/paste

### ISSUE THREAD

**Issue by supakeen** [Kwpolska/pygments_better_html#1]
Hey,

as mentioned here https://github.com/supakeen/pinnwand/issues/67 when copy pasting text that was formatted with the "table" line numbers blank lines disappear.

I'd like to make PR for this but do you have a preferred solution? Perhaps we can in some way hint the browser to not leave out empty tds.

**Comment by Kwpolska** [comment]
I looked at GitHub’s solution:

```
<tr>
        <td id="L2" class="blob-num js-line-number" data-line-number="2"></td>
        <td id="LC2" class="blob-code blob-code-inner js-file-line"><span class=pl-s>&quot;&quot;&quot;Demo for BetterHTMLFormatter.&quot;&quot;&quot;</span></td>
      </tr>
      <tr>
        <td id="L3" class="blob-num js-line-number" data-line-number="3"></td>
        <td id="LC3" class="blob-code blob-code-inner js-file-line">
</td>
      </tr>
```

So, if the line is blank, we need to put a `\n` in our `<code>` tag.
